quarkus.web-bundler.bundle.app=true
quarkus.web-bundler.bundle.components=true
quarkus.web-bundler.bundle.components.key=app
quarkus.web-bundler.bundle.components.qute-tags=true

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/Security/login
quarkus.http.auth.form.landing-page=/
quarkus.http.auth.form.error-page=

quarkus.datasource.db-kind=postgresql

hofkiinsewundun.footer-message=<p>Copyright &copy; 2026 Jomar Milan.</p>